# config.yaml
path: /Users/petrlutkin/Desktop/cvr_october_29_30/data_set # Путь к папке с вашим датасетом
train: /Users/petrlutkin/Desktop/cvr_october_29_30/data_set/images # Путь к папке с тренировочными изображениями
val: /Users/petrlutkin/Desktop/cvr_october_29_30/images # Путь к папке с валидационными изображениями
nc: 1 # Укажите количество классов в вашем датасете
names: ['traffic light'] # Список с названиями классов
